services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami
    env_file: ".env"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      DATABASE_TYPE: postgresql
    networks:
      - nginx
      - local
    depends_on:
      db:
        condition: service_healthy
    init: true
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl http://localhost:3000/api/heartbeat" ]
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    env_file: ".env"
    volumes:
      - ./umami-db-data:/var/lib/postgresql/data
    networks:
      - local
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  nginx:
    external: true
    name: nginx
  local: